### ISSUE TITLE
react: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by kappanjoe** [gagataiga/Phone-Review-App#35]
See following console warning:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Radio`. See https://reactjs.org/link/warning-keys for more information.
    at Radio (http://localhost:3000/static/js/bundle.js:1106:5)
    at div
    at div
    at div
    at div
    at Form (http://localhost:3000/static/js/bundle.js:1879:82)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:42040:5)
    at RenderErrorBoundary (http://localhost:3000/static/js/bundle.js:41991:5)
    at Routes (http://localhost:3000/static/js/bundle.js:42530:5)
    at Router (http://localhost:3000/static/js/bundle.js:42468:15)
    at RouterProvider (http://localhost:3000/static/js/bundle.js:42314:5)
```

Appears on the following components:
- [ ] `Homepage`
- [ ] `ReviewCard`
- [ ] `Radio`

**Comment by jayanth-kumar-morem** [comment]
Hi @kappanjoe , I would like to take this up, can you assign me to this

**Comment by aasimtaif** [comment]
Hi @kappanjoe i would like to resolve the issue ,can you assign it to me
